import { Roboto, Spectral, Playfair_Display } from 'next/font/google';
import type { Metadata } from "next";
import { cn } from '@/lib/utils';

import { Header } from '@/components/shared/header';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
  style: ['normal'],
  subsets: ['cyrillic'],
  display: 'swap',
})

const playfair = Playfair_Display({
  weight: ['400', '500', '700'],
  variable: '--font-playfair',
  style: ['normal'],
  subsets: ['cyrillic'],
  display: 'swap',
})

const spectral = Spectral({
  weight: ['400', '500', '700'],
  variable: '--font-spectral',
  style: ['normal'],
  subsets: ['cyrillic'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={
          cn(roboto.variable, playfair.variable, spectral.variable,
            'relative scrollbar before:absolute before:bg-[url("/pattern/pattern_gray.svg")] before:w-full before:h-full before:z-[-1] before:opacity-10 bg-background'
          )}>
        <Header />
        {children}
      </body>
    </html>
  );
}
